name: library_book_finde
description: "Aplicaci√≥n simple para escanear secciones de biblioteca"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  http: ^1.2.0
  path_provider: ^2.1.2
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Prueba1.jpg
    - assets/Prueba2.jpg
    - assets/Prueba3.jpg
